In [1]:
import pandas as pd

In [2]:
col_names = ["Age", "Gender", "Current_residence", "District", "Parent_occupation", "Displacement", 
             "Displaced_months", "Parent_current_employment", "Experiencing_bombs", "Family_member_loss", 
             "House_destruction", "Separated_from_parent", "Food/water_shortages", "Sleeping_before", 
             "Hypervigilance_after", "Nightmares_before", "Nightmares_after", "Worry/fear_before", 
             "Worry/fear_after", "Aggressive_behavior_before", "Aggressive_behavior_after", 
             "Family/friends_withdrawal_before", "Family/friends_withdrawal_after", "Mood swings_before", 
             "Mood_swings_after", "Avoid_war_topics_after", "Mental_health_curently", 
             "Coping_family_and_friends", "Coping_playing_games/sports", "Coping_drawing/writing/reading", 
             "Coping_religious_practices", "Coping_avoidance_of_triggers", "Received_psychological_support", 
             "Effectiveness", "Attend_school_during", "Attend_school_currently", "Academic_performance_after", 
             "Participation_in_social_activities", "Current_need_of_psychological_support", 
             "Current_need_of_educational_materials", "Current_need_of_safe_housing", 
             "Current_need_of_medical_care", "Current_need_of_food/water"]

df = pd.read_excel(io = "QA (Responses).xlsx", skiprows = 1, header = None, names = col_names)

df

,Age,Gender,Current_residence,District,Parent_occupation,Displacement,Displaced_months,Parent_current_employment,Experiencing_bombs,Family_member_loss,...,Effectiveness,Attend_school_during,Attend_school_currently,Academic_performance_after,Participation_in_social_activities,Current_need_of_psychological_support,Current_need_of_educational_materials,Current_need_of_safe_housing,Current_need_of_medical_care,Current_need_of_food/water
0,8,1,1,1,3,2,0,3,2,2,...,0,1,1,2,1,3,2,2,2,2
1,8,2,1,4,1,1,2,1,1,2,...,0,2,1,1,1,2,2,2,2,2
2,9,2,1,3,1,1,2,1,1,2,...,0,2,1,4,2,3,1,1,1,3
3,8,1,1,4,1,1,2,1,1,2,...,0,4,1,1,1,1,2,2,2,2
4,8,2,2,3,1,1,4,2,2,1,...,0,4,1,5,2,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,8,2,1,4,1,1,2,1,1,2,...,0,4,1,1,1,2,2,2,2,2
131,9,1,2,8,1,1,2,1,1,1,...,0,4,2,2,1,2,2,2,2,2
132,8,2,2,4,1,1,1,1,1,2,...,2,2,2,1,2,2,2,2,2,2
133,10,1,1,5,1,1,5,2,1,2,...,0,2,2,2,2,3,2,2,2,2
134,10,1,1,4,1,1,3,1,1,2,...,0,2,1,1,1,2,2,2,2,2

In [3]:
mental_health_bins = [0, 4, 7, 10]
mental_health_labels = ['Needs help', 'Stable', 'Thriving']
df["Mental_health_category"] = pd.cut(df["Mental_health_curently"], bins = mental_health_bins, labels = mental_health_labels, include_lowest = True, right=True)
df.drop("Mental_health_curently", axis = 1, inplace=True)

In [6]:
df.to_csv("QA_encoded.csv")